const ERROR_FORBIDDEN = 403;
const ERROR_NOT_FOUND = 404;
const ERROR_BAD_REQUEST = 400;
const ERROR_SERVER_ERROR = 500;
const CREATED_SUCCESS = 201;

module.exports = {
  ERROR_FORBIDDEN,
  ERROR_NOT_FOUND,
  ERROR_BAD_REQUEST,
  ERROR_SERVER_ERROR,
  CREATED_SUCCESS,
};
